name: Packer Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ValidatePackerFile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./Packer/ami.pkr.hcl
